name: Deploy to github pages

on:
push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '12'

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: npm ci

      - name: Run deploy script
        run: |
          git config user.name "DezignDezire" && git config user.email "philipp.lenz@hotmail.com"
          npm run gh-pages-deploy